# generated with 'apt-mark showauto' on Ubuntu 20.04.1
AUTO_PACKAGES=\
	accountsservice \
	adduser \
	alsa-topology-conf \
	alsa-ucm-conf \
	amd64-microcode \
	apparmor \
	apport \
	apport-symptoms \
	apt \
	apt-utils \
	at \
	bash-completion \
	bc \
	bcache-tools \
	bind9-dnsutils \
	bind9-host \
	bind9-libs \
	bolt \
	bsdmainutils \
	bsdutils \
	btrfs-progs \
	busybox-initramfs \
	busybox-static \
	byobu \
	bzip2 \
	ca-certificates \
	cloud-guest-utils \
	cloud-initramfs-copymods \
	cloud-initramfs-dyn-netconf \
	command-not-found \
	console-setup \
	console-setup-linux \
	coreutils \
	cpio \
	crda \
	cron \
	cryptsetup \
	cryptsetup-bin \
	cryptsetup-initramfs \
	cryptsetup-run \
	curl \
	dbus \
	dbus-user-session \
	dconf-gsettings-backend \
	dconf-service \
	debconf \
	debconf-i18n \
	debianutils \
	dirmngr \
	distro-info-data \
	dmeventd \
	dmidecode \
	dmsetup \
	dosfstools \
	dpkg \
	e2fsprogs \
	eatmydata \
	ed \
	eject \
	ethtool \
	file \
	finalrd \
	fonts-ubuntu-console \
	friendly-recovery \
	ftp \
	fuse \
	fwupd \
	fwupd-signed \
	gawk \
	gcc-10-base \
	gdisk \
	gettext-base \
	gir1.2-glib-2.0 \
	gir1.2-packagekitglib-1.0 \
	git \
	git-man \
	glib-networking \
	glib-networking-common \
	glib-networking-services \
	gnupg \
	gnupg-l10n \
	gnupg-utils \
	gpg \
	gpg-agent \
	gpg-wks-client \
	gpg-wks-server \
	gpgconf \
	gpgsm \
	gpgv \
	groff-base \
	grub-common \
	grub-efi-amd64-bin \
	grub2-common \
	gsettings-desktop-schemas \
	hdparm \
	htop \
	info \
	init-system-helpers \
	initramfs-tools \
	initramfs-tools-bin \
	initramfs-tools-core \
	install-info \
	intel-microcode \
	iproute2 \
	iptables \
	iputils-ping \
	iputils-tracepath \
	irqbalance \
	isc-dhcp-client \
	isc-dhcp-common \
	iso-codes \
	iucode-tool \
	iw \
	kbd \
	keyboard-configuration \
	klibc-utils \
	kmod \
	kpartx \
	krb5-locales \
	landscape-common \
	language-selector-common \
	less \
	libaccountsservice0 \
	libacl1 \
	libaio1 \
	libapparmor1 \
	libappstream4 \
	libapt-pkg6.0 \
	libarchive13 \
	libargon2-1 \
	libasn1-8-heimdal \
	libasound2 \
	libasound2-data \
	libassuan0 \
	libatm1 \
	libattr1 \
	libaudit-common \
	libaudit1 \
	libblkid1 \
	libbrotli1 \
	libbsd0 \
	libbz2-1.0 \
	libc-bin \
	libc6 \
	libcanberra0 \
	libcap-ng0 \
	libcap2 \
	libcap2-bin \
	libcbor0.6 \
	libcom-err2 \
	libcrypt1 \
	libcryptsetup12 \
	libcurl3-gnutls \
	libcurl4 \
	libdb5.3 \
	libdbus-1-3 \
	libdbus-glib-1-2 \
	libdconf1 \
	libdevmapper-event1.02.1 \
	libdevmapper1.02.1 \
	libdns-export1109 \
	libdrm-common \
	libdrm2 \
	libeatmydata1 \
	libedit2 \
	libefiboot1 \
	libefivar1 \
	libelf1 \
	liberror-perl \
	libestr0 \
	libevent-2.1-7 \
	libexpat1 \
	libext2fs2 \
	libfastjson4 \
	libffi7 \
	libfido2-1 \
	libfl2 \
	libfreetype6 \
	libfribidi0 \
	libfuse2 \
	libfwupd2 \
	libfwupdplugin1 \
	libgcab-1.0-0 \
	libgcc-s1 \
	libgcrypt20 \
	libgdbm-compat4 \
	libgdbm6 \
	libgirepository-1.0-1 \
	libglib2.0-0 \
	libglib2.0-bin \
	libglib2.0-data \
	libgmp10 \
	libgnutls30 \
	libgpg-error0 \
	libgpgme11 \
	libgpm2 \
	libgssapi-krb5-2 \
	libgssapi3-heimdal \
	libgstreamer1.0-0 \
	libgudev-1.0-0 \
	libgusb2 \
	libhcrypto4-heimdal \
	libheimbase1-heimdal \
	libheimntlm0-heimdal \
	libhogweed5 \
	libhx509-5-heimdal \
	libicu66 \
	libidn2-0 \
	libip4tc2 \
	libip6tc2 \
	libisc-export1105 \
	libisns0 \
	libjson-c4 \
	libjson-glib-1.0-0 \
	libjson-glib-1.0-common \
	libk5crypto3 \
	libkeyutils1 \
	libklibc \
	libkmod2 \
	libkrb5-26-heimdal \
	libkrb5-3 \
	libkrb5support0 \
	libksba8 \
	libldap-2.4-2 \
	libldap-common \
	liblmdb0 \
	liblocale-gettext-perl \
	libltdl7 \
	liblvm2cmd2.03 \
	liblz4-1 \
	liblzma5 \
	liblzo2-2 \
	libmagic-mgc \
	libmagic1 \
	libmaxminddb0 \
	libmnl0 \
	libmount1 \
	libmpdec2 \
	libmpfr6 \
	libmspack0 \
	libncurses6 \
	libncursesw6 \
	libnetfilter-conntrack3 \
	libnetplan0 \
	libnettle7 \
	libnewt0.52 \
	libnfnetlink0 \
	libnftnl11 \
	libnghttp2-14 \
	libnl-3-200 \
	libnl-genl-3-200 \
	libnpth0 \
	libnss-systemd \
	libntfs-3g883 \
	libnuma1 \
	libogg0 \
	libp11-kit0 \
	libpackagekit-glib2-18 \
	libpam-cap \
	libpam-modules \
	libpam-modules-bin \
	libpam-runtime \
	libpam-systemd \
	libpam0g \
	libparted2 \
	libpcap0.8 \
	libpci3 \
	libpcre2-8-0 \
	libpcre3 \
	libperl5.30 \
	libpipeline1 \
	libplymouth5 \
	libpng16-16 \
	libpolkit-agent-1-0 \
	libpolkit-gobject-1-0 \
	libpopt0 \
	libprocps8 \
	libproxy1v5 \
	libpsl5 \
	libpython3-stdlib \
	libpython3.8 \
	libpython3.8-minimal \
	libpython3.8-stdlib \
	libreadline5 \
	libreadline8 \
	libroken18-heimdal \
	librtmp1 \
	libsasl2-2 \
	libsasl2-modules \
	libsasl2-modules-db \
	libseccomp2 \
	libselinux1 \
	libsemanage-common \
	libsemanage1 \
	libsepol1 \
	libsgutils2-2 \
	libsigsegv2 \
	libslang2 \
	libsmartcols1 \
	libsmbios-c2 \
	libsoup2.4-1 \
	libsqlite3-0 \
	libss2 \
	libssh-4 \
	libssl1.1 \
	libstdc++6 \
	libstemmer0d \
	libsystemd0 \
	libtasn1-6 \
	libtdb1 \
	libtext-charwidth-perl \
	libtext-iconv-perl \
	libtext-wrapi18n-perl \
	libtinfo6 \
	libtss2-esys0 \
	libuchardet0 \
	libudev1 \
	libunistring2 \
	libunwind8 \
	liburcu6 \
	libusb-1.0-0 \
	libutempter0 \
	libuuid1 \
	libuv1 \
	libvorbis0a \
	libvorbisfile3 \
	libwind0-heimdal \
	libwrap0 \
	libx11-6 \
	libx11-data \
	libxau6 \
	libxcb1 \
	libxdmcp6 \
	libxext6 \
	libxml2 \
	libxmlb1 \
	libxmlsec1 \
	libxmlsec1-openssl \
	libxmuu1 \
	libxslt1.1 \
	libxtables12 \
	libyaml-0-2 \
	libzstd1 \
	linux-base \
	linux-firmware \
	linux-headers-5.4.0-42 \
	linux-headers-5.4.0-42-generic \
	linux-headers-generic \
	linux-image-5.4.0-42-generic \
	linux-image-generic \
	linux-modules-5.4.0-42-generic \
	linux-modules-extra-5.4.0-42-generic \
	locales \
	login \
	logrotate \
	logsave \
	lsb-base \
	lsb-release \
	lshw \
	lsof \
	ltrace \
	lvm2 \
	lxd-agent-loader \
	lz4 \
	man-db \
	manpages \
	mawk \
	mdadm \
	mime-support \
	mokutil \
	mount \
	mtr-tiny \
	multipath-tools \
	nano \
	ncurses-term \
	netbase \
	netcat-openbsd \
	netplan.io \
	networkd-dispatcher \
	ntfs-3g \
	open-iscsi \
	open-vm-tools \
	openssh-client \
	openssh-sftp-server \
	openssl \
	os-prober \
	overlayroot \
	packagekit \
	packagekit-tools \
	parted \
	passwd \
	pastebinit \
	patch \
	pci.ids \
	pciutils \
	perl \
	perl-base \
	perl-modules-5.30 \
	pinentry-curses \
	plymouth \
	plymouth-theme-ubuntu-text \
	policykit-1 \
	pollinate \
	popularity-contest \
	powermgmt-base \
	procps \
	psmisc \
	publicsuffix \
	python-apt-common \
	python3 \
	python3-apport \
	python3-apt \
	python3-attr \
	python3-automat \
	python3-blinker \
	python3-certifi \
	python3-cffi-backend \
	python3-chardet \
	python3-click \
	python3-colorama \
	python3-commandnotfound \
	python3-configobj \
	python3-constantly \
	python3-cryptography \
	python3-dbus \
	python3-debconf \
	python3-debian \
	python3-distro \
	python3-distro-info \
	python3-distupgrade \
	python3-distutils \
	python3-entrypoints \
	python3-gdbm \
	python3-gi \
	python3-hamcrest \
	python3-httplib2 \
	python3-hyperlink \
	python3-idna \
	python3-importlib-metadata \
	python3-incremental \
	python3-jinja2 \
	python3-json-pointer \
	python3-jsonpatch \
	python3-jsonschema \
	python3-jwt \
	python3-keyring \
	python3-launchpadlib \
	python3-lazr.restfulclient \
	python3-lazr.uri \
	python3-lib2to3 \
	python3-markupsafe \
	python3-minimal \
	python3-more-itertools \
	python3-netifaces \
	python3-newt \
	python3-oauthlib \
	python3-openssl \
	python3-pkg-resources \
	python3-problem-report \
	python3-pyasn1 \
	python3-pyasn1-modules \
	python3-pyrsistent \
	python3-requests \
	python3-requests-unixsocket \
	python3-secretstorage \
	python3-serial \
	python3-service-identity \
	python3-setuptools \
	python3-simplejson \
	python3-six \
	python3-software-properties \
	python3-systemd \
	python3-twisted \
	python3-twisted-bin \
	python3-update-manager \
	python3-urllib3 \
	python3-wadllib \
	python3-yaml \
	python3-zipp \
	python3-zope.interface \
	python3.8 \
	python3.8-minimal \
	readline-common \
	rsync \
	rsyslog \
	run-one \
	sbsigntool \
	screen \
	secureboot-db \
	sed \
	sensible-utils \
	sg3-utils \
	sg3-utils-udev \
	shared-mime-info \
	shim \
	snapd \
	software-properties-common \
	sosreport \
	sound-theme-freedesktop \
	squashfs-tools \
	ssh-import-id \
	strace \
	sudo \
	systemd \
	systemd-sysv \
	systemd-timesyncd \
	tar \
	tcpdump \
	telnet \
	thermald \
	thin-provisioning-tools \
	time \
	tmux \
	tpm-udev \
	tzdata \
	ubuntu-advantage-tools \
	ubuntu-keyring \
	ubuntu-release-upgrader-core \
	ucf \
	udev \
	ufw \
	unattended-upgrades \
	update-manager-core \
	update-notifier-common \
	usb.ids \
	usbutils \
	util-linux \
	uuid-runtime \
	vim \
	vim-common \
	vim-runtime \
	vim-tiny \
	wget \
	whiptail \
	wireless-regdb \
	xauth \
	xdg-user-dirs \
	xfsprogs \
	xkb-data \
	xxd \
	xz-utils \
	zerofree \
	zlib1g

# generated with 'apt-mark showmanual' on Ubuntu 20.04.1
MANUAL_PACKAGES=\
	base-files \
	base-passwd \
	bash \
	cloud-init \
	dash \
	diffutils \
	efibootmgr \
	fdisk \
	findutils \
	grep \
	grub-efi-amd64 \
	grub-efi-amd64-signed \
	gzip \
	hostname \
	init \
	libdebconfclient0 \
	libfdisk1 \
	libsodium23 \
	linux-generic \
	ncurses-base \
	ncurses-bin \
	openssh-server \
	python3-nacl \
	python3-pymacaroons \
	shim-signed \
	sysvinit-utils \
	ubuntu-minimal \
	ubuntu-server \
	ubuntu-standard
